language: node_js

node_js:
  - '6'

before_script:
  - npm install -g grunt-cli bower
  - bower install

script: grunt ci --verbose

env:
  global:
    - secure: o7uB6fF7d8uu+4CtXzQ69HrwAJnHHmlAq2Pg5pyanCkjk0pGEqOUI+cDXBL/MpPVTPQGk78Soq0/gHcyeCsQmpTc9Ww8fDae02VzCIEwjPuihfDU291V8NHBD9cBkA82CtWYtYfT005TqySrrCkguLo2qr3sNjOJG86lj5Zn1KXZw9vRezRTQA3oXngfPOJSEAsgVVTKXUPeApXoZliaAslqQs8G2tzxW2cEBHE3Qs5rZKkdv9a2WC4+MvTdABIy9+PC6FNbBxEruoEWHMen50LBrOgzrJ6URXFvkf50BuhG8hH8t3SAJWt3zS6+Txot8z1qih8eTWKp8NM43IBNZrBAEJv4Z7rg8kGA1BOloK2XBMgQ0R/o+TjMjb+/g4L8etbrYzGVj3Fgynohl6MnD7LUoQYZDlwrm1DgCJijgUl7unUwG3OAvSPi/1ZN1PgYNr3PQy/850jurDshMiJoyOyld0CZDYhQKu1d3j3u3+HnMdUsOXHMX8mU59kjg5By5tDM/z4n4lS/Wn71FVrQgWzUAlzS6Oi7NMxzg8WcF88HT21kfHX+FfBgLa5K9BEMI9BQpmytqj2X4D8fBL1QKeAel6fglgEuNJVpwKJPdFxbR4gTk2/0DWMIbvWIjNO9thh+tZ09cIq/tD1aJ+Hs8lwjYXt/ISNJo8n3I0K7U5M=
    - secure: puvL8GSrmQygXF09Q8g1DoHb8PRajm4+keOBFsGKjBjRdkttsIxQ2V13IZvwdmIb+icH0XcwcOKS1MVKEGic9sixDglObthSO2koNI1rfyYqMWJ6Ye4NAOvnZ2w2B8LLJDkTjmp0dvJYHTHiDPNnb2zjbGsFHb5dVNdmds3hTADXdBGPbZV8szQ8x8doeL55Eps/ZYhPTu6KfA/yvjy/7UXQ9/0PqWnI09I5e6qdtHMPtAuFKRGasZdMsPW+vYni6MTdKOIG5dyutm3mAMD903ozx/yiaIiMavDRcPSbC4Aflh4E7Z87Pl9oQnX3YMnOBbC4Nv4Fkg9RVHCvaVU09QhKVzhz3Smibx9BsyTIx1krV9XbDJqzSI94oSVcl+kzx2U+FmxsVfvDaswUZFjSmJYGKvbnPPhUVnEdNHfTNJ3BbH7phFXjavNr87nueWxK3KDRritKegque3HhaCFpzfgZzjwIN2SO2RA5vPbsn7iCyHpY8ISazubfuEFX4vUyvK3QAX8bDdPCtVGDQmd1m3mEq2nx+7muaA8BhLjjVTbAk2dQtklLwoVyyIztzggbwHQdNiUzQk64RwerZomhokQsnkaaGayQpFQTfycsi9NDSArsOafp0vLsp6kKl/GKUKuThO2B9jXkRNXZY75WlQvvNfhr53vA+Tr96EGwLTQ=
